### ISSUE TITLE
Missing hash_linux.h header

### ISSUE THREAD

**Issue by sameershende** [Azure/azure-storage-cpp#10]
Hi,
    We are missing the has_linux.h header. Would you please check it in. It doesn't compile under Linux without this header. 

https://github.com/Azure/azure-storage-cpp/tree/master/Microsoft.WindowsAzure.Storage/includes/wascore

	The code that uses this is in:
https://github.com/Azure/azure-storage-cpp/blob/master/Microsoft.WindowsAzure.Storage/includes/wascore/streams.h

#include "wascore/basic_types.h"
#include "streambuf.h"

#ifdef WIN32
#include "hash_windows.h"
#else
#include "hash_linux.h"
#endif

   Thanks!
   - Sameer

**Comment by slepox** [comment]
@sameershende, version 0.4.0  is released last December which supports Linux officially, please take a try.

**Comment by sehe** [comment]
@slepox I specifically noted that the release notes mention that it "supports building on Linux". Can you confirm that you indeed /mean/ that the library itself (i.e. using it) is _officially_ supported on Linux?

**Comment by slepox** [comment]
Yes, it is officially supported.

**Comment by sehe** [comment]
@slepox That's great news! 

I feel that Microsoft could improve the communication about these awesome C++ libraries a bit.

Is there an official channel to subscribe to? Does Microsoft get the word out somewhere I didn't find yet?

For one, I would never have known about the Linux support except because I had actively subscribed to issue #12 /and/ I spotted the github merge notification.

Next, I have **[advertised this very welcome news via Twitter](https://twitter.com/sehetw/status/540405902080503809)** (where very few people appeared to be aware of the project/release), staying very true to the release notes: 

> `Woot! #Microsoft @Azure Storage Client #cpp library now supports building [note the wording!] on @Linux - That's big` https://github.com/Azure/azure-storage-cpp/pull/14

Turns out I would not have had to be nearly as cautious with that wording.

**Comment by slepox** [comment]
Thanks a lot for your support, @sehe! [Microsoft Azure Storage Team Blog](http://blogs.msdn.com/b/windowsazurestorage/archive/2014/12/22/using-azure-storage-on-linux.aspx) usually announces the latest news about Azure storage, and welcome to subscribe:)
