### ISSUE TITLE
Support iOS compilation ?

### ISSUE THREAD

**Issue by epot** [Azure/azure-storage-cpp#107]
This is more a question than an issue: since the iOS SDK is in complete standy, is it possible (and is there a guide) to compile this component for iOS ? It seems it is perfectly doable for its cpprestsdk dependency for instance.

**Comment by JasonYang-MSFT** [comment]
For iOS DK, you can refer to https://github.com/Azure/azure-storage-ios.

Yes, it is possible to compile this component for iOS since our depenency library(cpprestsdk) is available for iOS: https://github.com/Microsoft/cpprestsdk/wiki/How-to-build-for-iOS. But we haven't tried and I believe that there might be some compile issues we need to fix for iOS.

If you are interested, you can submit a PR to support iOS. We already merged a PR to support osx in June(https://github.com/Azure/azure-storage-cpp/pull/75).

**Comment by pemari-msft** [comment]
So we actually have tried to do this in the past. Besides a large number of changes required for compilation, the library is prohibitively large. Generally, it was determined that creating a dependency that caused the final app to be so large wasn't viable. In some cases it even would be an issue regarding the size limits imposed by Apple for app verification. 

That is to say, I don't recommend it and it certainly won't be a scenario this library claims to support.

**Comment by epot** [comment]
Ok, thanks that's clear. That is a shame that the ios library is currently so poor...
