### ISSUE TITLE
Errors while integrating to Android NDK

### ISSUE THREAD

**Issue by t-shroy** [Azure/azure-storage-cpp#125]
Many dependencies are not resolved even after adding CPPREST SDK , android studio is giving errors while trying to run the native c++ codes. Examples -

uuid/uuid.h not found.

undefined reference to `azure::storage::cloud_blob_container::cloud_blob_container(azure::storage::storage_uri)

And more such undefined reference problem.

**Comment by JasonYang-MSFT** [comment]
Hi @t-shroy ,

uuid/uuid.h is used on Linux platform. Since you are using android studio, _Win32 is not defined so it will go to linux's parts compliation:
https://github.com/Azure/azure-storage-cpp/blob/9208c7c4b57a2efa9ce059d754ebd49960c45021/Microsoft.WindowsAzure.Storage/includes/wascore/basic_types.h#L33

Besides c++ sdk, we also have an SDK designed for android, maybe you want to try this: https://github.com/Azure/azure-storage-android
