### ISSUE TITLE
Is there a way to test a blob endpoint before an operation can be performed?

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#190]
Hi,

If a bad endpoint is passed to me, such as "https://bad.blob.core.windows.net", the following code block won't generate any exception or return anything which would indicate it is a bad end point:

    cloud_storage_account storage_account = cloud_storage_account::parse(connection_string.c_str());
    auto blob_client = storage_account.create_cloud_blob_client(options);

I am wondering if there is a way to detect that bad URL before it goes further down the code path to download a stream or a blob.

Thanks,

Yang

**Comment by jasonzio** [comment]
Those methods don’t actually do anything; they’re simply setting up data structures.

You actually have to perform an action on storage for real before you can know if your connection string (endpoint plus credentials) is valid. There’s nothing that prevents an authorized admin from rolling the keys on the storage account after you’ve drawn the tentative conclusion that your credentials are good.

Azure storage is just like many other distributed systems: you can’t answer the question without actually trying to do the actual work, so you’re best off investing in proper error detection every time (!!) you use the endpoint/credentials to access storage. Even if the first operation succeeds, a subsequent operation may nonetheless fail.

My preferred “fail fast” test is simply fetching the attributes on a blob in the container. Whether the blob exists or not is irrelevant; you’re looking for “Invalid credentials” rather than the actual results. If your connection string is invalid, you’ll get the appropriate error (rather than either the file attributes or a “No such file” error). If I have a SAS token as credentials, I can do a fast HTTPS HEAD operation on a blob to which the SAS applies, avoiding the storage API completely.
