### ISSUE TITLE
Best way to upload from std::basic_istream<char>

### ISSUE THREAD

**Issue by howryu** [Azure/azure-storage-cpp#196]
It seems that azure storage cpp did not use cpp standard iostream class, but create its own iostream class. I have a std::basic_iostream<char> object that I want to upload to blob storage. However, `cloud_blob.upload_from_stream()` method takes a `concurrency::streams::basic_istream` object. I wonder what's the best to convert from my std::basic_istream class to azure specific basic_istream. Do I need to implement my own streambuf object as well?

**Comment by katmsft** [comment]
There are two problems here:
1.  concurrency::streams::basic_istream is actually a CPPRest defined type, not a azure storage cpp defined type. We are only adapting this usage because we use CPPRest as our HTTP client. So this should be a CPPRest issue rather than azure storage cpp issue.
2.  `cloud_blob.upload_from_stream()` takes `concurrency::streams::istream`, which is a `typedef` for `concurrency::streams::basic_istream<uint8_t>`. You can use its derived class [`concurrency::streams::stdio_istream<uint8_t>`](http://microsoft.github.io/cpprestsdk/class_concurrency_1_1streams_1_1stdio__istream.html) to neatly convert `std::basic_istream<uint8_t>` to CPPRest's customized stream type, but you'll have to convert `std::basic_istream<char>` to `std::basic_istream<uint8_t>` yourself.

**Comment by howryu** [comment]
Thanks for your info. `stdio_istream` worked for me.
