### ISSUE TITLE
Clarify what version of the REST SDK  current release 5.0 depends on

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-storage-cpp#212]
Anything higher than cpp rest sdk 2.9.1 and above does not seem to work due to the following compilation error:
azure-storage-cpp/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: ‘do_while’ is not a member of ‘pplx::details’
return pplx::details::do_while(instance -> pplx::task
^
****pplx::details::do_while is no longer defined after cpp rest sdk 2.9.1 in include/pplx/pplxtask.h inside namespace details.

Can somebody please clarify if that observation is correct?  Do we need when we will be able to support newer version of the REST SDK and port all the bug fixes from there?

Thanks,

Yang

**Comment by katmsft** [comment]
This is because the namespace for the _do_while is changed from Concurrency::details to pplx::details in cpprestsdk 2.10.3

Reference:

https://github.com/Microsoft/cpprestsdk/blob/v2.10.0/Release/include/cpprest/astreambuf.h#L25

https://github.com/Microsoft/cpprestsdk/blob/v2.10.1/Release/include/cpprest/astreambuf.h#L25

https://github.com/Microsoft/cpprestsdk/blob/v2.10.2/Release/include/cpprest/astreambuf.h#L25

https://github.com/Microsoft/cpprestsdk/blob/v2.10.3/Release/include/cpprest/astreambuf.h#L25

Please update to cpprest 2.10.3, there shouldn't be issues like this.

**Comment by katmsft** [comment]
Also, starting from 5.1.1, a table will be provided in Readme declaring the tested cpprestsdk version for each release of the REST sdk, thanks for the suggestion.

**Comment by katmsft** [comment]
Currently the cpprestsdk version is specified in REAME.md, so closing this issue.
