### ISSUE TITLE
Support for installing in MacOSx

### ISSUE THREAD

**Issue by mohiuddin-shuvo** [Azure/azure-storage-cpp#27]
How can i install this library in MacOSx? Do you have support for that?

**Comment by zesme** [comment]
OS X uses clang for compilation, aside from that, I don't believe there are any problems

I managed to compile it yesterday by using the exact same flags that the makefile provides if you are using GNU, but using clang. Now, I'm no make expert, and just got started with C++, so there might have been some problems with this method.

I did get lots of warnings from clang, but no errors...

**Comment by hanzhumsft** [comment]
@mohiuddin-shuvo We are not support Mac OS X officially. In the future we'll consider supporting it.

@zesme If you managed to compile and run our library on OS X, we are happy to see the PR and your contribution.

**Comment by guysherman** [comment]
I have managed to compile the library so far. I think some of the issues were my setup, and some are the cmake files. Most of the fixes came from the makefiles generated for casablanca. I'm in the process of modifying the cmake files to deal with OSX.

The biggest issue is that you need to set -stdlib=libc++ in the cflags, otherwise clang thinks it doesn't support atomics, and then you can't build the bits that rely on casablanca, that fixes the errors relating to ...casablanca.../pplxinterface.h.

I also had to manually add in some compile and link flags to tell it about openssl and gettext, which I had installed with homebrew, but weren't found by cmake because they are "keg only". This could be down to how I invoked cmake in the first place.

Finally, I had to add -DBOOST_LOG_DYN_LINK to the cxx and ld flags otherwise it failed linking with boost log.

I haven't tried to run the tests yet, so a PR is a little way off.

**Comment by hanzhumsft** [comment]
Thanks @guysherman for the PR #75.  It's been merged to our dev branch, so please check OS X support on that branch to unblock you.

Please note right now we are not officially supporting OS X in terms of quality, stress, and test coverage. If we keep receiving requests on OS X support, we will consider adding OS X to our test matrix and guarantee the same level of quality as other platforms.
